### ISSUE TITLE
Add Cargo/Other Bays to the resources of a fitting

### ISSUE THREAD

**Issue by r2h3** [Lionear/Eveworkbench.Issues#11]
It would be really useful for atleast (newish) miners to see the cargo space of mining barge fittings to get a better insight on why to choose one fitting over another.

As adding this might make the whole resource sidebar feel bloated i would recommend creating a tab in the "resources" Section so you can switch from the resistance patterns to a list (similar style to the resistances) of Bays the ship has.

**Comment by Lionear** [comment]
@r2h3 you mean to have the cargo bay as a tab at the right?

**Comment by r2h3** [comment]
here's a prototype to illustrate what i meant
![bays](https://user-images.githubusercontent.com/15652175/56436874-aeb67b80-62dd-11e9-9eed-634b51c71352.PNG)

Forgot to change "Ressources" to "Resists"

**Comment by Lionear** [comment]
We might check this out. Will attach it to a milestone yet but the idea is good!

**Comment by raymondkrahwinkel** [comment]
The special bays like Ore Hold, Fleet Hangar, Fuel Bay, Ship Maintenance Bay i think should be first added like the cargo bay now is, because we cannot clearly put something in the fleet hangar or other extra bays, because the EFT doesn't support it, so we have to guess where to place something...

The fighter bays we will look into, because this is information we can get and show without guessing work and is also needed later on for DPS calculations.
