### ISSUE TITLE
Can't see the required skills in the pop-over

### ISSUE THREAD

**Issue by Lionear** [Lionear/Eveworkbench.Issues#3]
When you have a lot of required skills left to train the pop-over will show/hide infinite

**Comment by r2h3** [comment]
it also does show this behaviour on Firefox 66.0.3 (64-Bit)
![vb5tX1z](https://user-images.githubusercontent.com/15652175/56098288-3fb4dd80-5eff-11e9-914f-aaf16daff207.gif)
useragent:
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0

This only happens if you lack quite a few skills as show in the gif. Testing on a character who is missing just 2 skills it works flawlessly.

**Comment by Lionear** [comment]
![image](https://user-images.githubusercontent.com/6653342/56467921-7e79f480-6425-11e9-86e0-2eb4ebfcd82a.png)
We will solve this by removing the popover functionality and make the skillbook icon clickable.

**Comment by Lionear** [comment]
Issue has been resolved and will be released with EWB 1.4.5
